repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.54.2
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-s, -w]
        files: \.go$

      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        files: \.go$

      - id: go-test
        name: go test
        entry: go
        language: system
        args: [test, -v, ./...]
        files: \.go$

      - id: go-mod-tidy
        name: go mod tidy
        entry: go
        language: system
        args: [mod, tidy]
        files: go\.(mod|sum)$

      - id: go-build
        name: go build
        entry: go
        language: system
        args: [build, ./...]
        files: \.go$
