# etcd-monitor configuration example
# Copy this file to config.yaml and customize for your environment

# etcd connection settings
etcd:
  endpoints:
    - "localhost:2379"
    - "localhost:22379"
    - "localhost:32379"
  dial_timeout: 5s

  # TLS configuration (optional)
  tls:
    enabled: false
    cert_file: "/path/to/cert.pem"
    key_file: "/path/to/key.pem"
    ca_file: "/path/to/ca.pem"
    insecure_skip_verify: false

# API server settings
api:
  host: "0.0.0.0"
  port: 8080
  timeout: 30s

  # CORS settings
  cors:
    enabled: true
    allowed_origins:
      - "*"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"

# Monitoring settings
monitoring:
  # Collection intervals
  health_check_interval: 30s
  metrics_interval: 10s
  watch_interval: 5s

  # Alert thresholds
  thresholds:
    max_latency_ms: 100
    max_database_size_mb: 8192
    min_available_nodes: 2
    max_leader_changes_per_hour: 3
    max_error_rate: 0.05  # 5%
    min_disk_space_percent: 10.0

# Alerting configuration
alerts:
  # Email notifications
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    from: "etcd-monitor@example.com"
    to:
      - "ops-team@example.com"
      - "sre-team@example.com"
    username: "your-email@example.com"
    password: "your-password"

  # Slack notifications
  slack:
    enabled: false
    webhook_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
    channel: "#etcd-alerts"
    username: "etcd-monitor"

  # PagerDuty notifications
  pagerduty:
    enabled: false
    integration_key: "your-integration-key"

  # Generic webhook
  webhook:
    enabled: false
    url: "https://your-webhook-endpoint.com/alerts"
    headers:
      Authorization: "Bearer your-token"

  # Console logging (for testing)
  console:
    enabled: true

# Benchmark settings
benchmark:
  enabled: false
  interval: 1h

  # Default benchmark configuration
  default:
    type: "mixed"  # write, read, mixed, range, delete, txn
    connections: 10
    clients: 10
    key_size: 32
    value_size: 256
    total_operations: 10000
    key_prefix: "/benchmark-test"
    target_leader: false
    rate_limit: 0  # 0 = unlimited

  # SLI/SLO targets
  slo:
    read_throughput: 40000    # ops/sec
    write_throughput: 20000   # ops/sec
    p99_latency_ms: 100       # milliseconds

# Data storage (for historical metrics)
storage:
  enabled: false
  type: "postgresql"  # postgresql, timescaledb

  postgresql:
    host: "localhost"
    port: 5432
    database: "etcd_monitor"
    user: "etcd_monitor"
    password: "your-password"
    ssl_mode: "disable"
    max_connections: 10

  # Retention policies
  retention:
    metrics: 90d      # Keep metrics for 90 days
    alerts: 30d       # Keep alert history for 30 days
    events: 30d       # Keep event logs for 30 days

# Logging
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "stdout"  # stdout, stderr, file
  file:
    path: "/var/log/etcd-monitor/app.log"
    max_size_mb: 100
    max_backups: 10
    max_age_days: 30
    compress: true

# Feature flags
features:
  multi_cluster: false
  backup_monitoring: false
  audit_logs: false
  prometheus_export: true
  grafana_dashboards: true
