version: '3.8'

services:
  # etcd cluster (3 nodes for HA)
  etcd1:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd1
    command:
      - /usr/local/bin/etcd
      - --name=etcd1
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd1:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster-state=new
      - --enable-v2=true
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd1-data:/etcd-data
    networks:
      - etcd-network

  etcd2:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd2
    command:
      - /usr/local/bin/etcd
      - --name=etcd2
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd2:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster-state=new
      - --enable-v2=true
    ports:
      - "22379:2379"
      - "22380:2380"
    volumes:
      - etcd2-data:/etcd-data
    networks:
      - etcd-network

  etcd3:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd3
    command:
      - /usr/local/bin/etcd
      - --name=etcd3
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd3:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - --initial-cluster-token=etcd-cluster
      - --initial-cluster-state=new
      - --enable-v2=true
    ports:
      - "32379:2379"
      - "32380:2380"
    volumes:
      - etcd3-data:/etcd-data
    networks:
      - etcd-network

  # etcd-monitor - our monitoring application
  etcd-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etcd-monitor
    ports:
      - "8080:8080"
    command:
      - "--endpoints=etcd1:2379,etcd2:2379,etcd3:2379"
      - "--api-host=0.0.0.0"
      - "--api-port=8080"
      - "--health-check-interval=30s"
      - "--metrics-interval=10s"
      - "--dial-timeout=5s"
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    networks:
      - etcd-network
    restart: unless-stopped

  # Prometheus - metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - etcd-network
    restart: unless-stopped

  # Grafana - visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - etcd-network
    restart: unless-stopped

networks:
  etcd-network:
    driver: bridge

volumes:
  etcd1-data:
  etcd2-data:
  etcd3-data:
  prometheus-data:
  grafana-data:
