# Pingap-Go Example Configuration

[basic]
name = "pingap-go"
threads = 4
grace_period = "30s"

# Upstream backend services
[upstreams.backend_api]
addrs = [
    "127.0.0.1:8001",
    "127.0.0.1:8002",
    "127.0.0.1:8003"
]
algorithm = "round_robin"
health_check = "http://127.0.0.1:8001/health"
health_check_interval = "10s"
connection_timeout = "10s"
read_timeout = "30s"
write_timeout = "30s"
idle_timeout = "90s"
max_idle_conns = 100
max_idle_conns_per_host = 10

[upstreams.backend_static]
addrs = ["127.0.0.1:9000"]
algorithm = "round_robin"
connection_timeout = "5s"

# Location definitions (routing rules)
[locations.api_v1]
upstream = "backend_api"
path = "/api/v1"
path_type = "prefix"
priority = 100
methods = ["GET", "POST", "PUT", "DELETE"]
rewrite = "/"
headers_add = [
    "X-Forwarded-Proto: https",
    "X-Request-Source: pingap-go"
]
headers_remove = ["Server"]

[locations.api_v1.proxy_set_headers]
Host = "api.internal.local"
X-Real-IP = "$remote_addr"

[locations.static_files]
upstream = "backend_static"
path = "/static"
path_type = "prefix"
priority = 50

[locations.health]
upstream = "backend_api"
path = "/health"
path_type = "exact"
priority = 200

# HTTP Server
[servers.http]
addr = "0.0.0.0:80"
locations = ["api_v1", "static_files", "health"]
access_log = "/var/log/pingap/access.log"
read_timeout = "30s"
write_timeout = "30s"
idle_timeout = "120s"
max_header_bytes = 1048576
enable_http2 = true

# HTTPS Server
[servers.https]
addr = "0.0.0.0:443"
locations = ["api_v1", "static_files"]
tls_cert = "/etc/pingap/certs/server.crt"
tls_key = "/etc/pingap/certs/server.key"
access_log = "/var/log/pingap/access_https.log"
enable_http2 = true

# Metrics
[metrics]
enabled = true
path = "/metrics"
addr = "127.0.0.1:9090"

# Tracing
[tracing]
enabled = false
endpoint = "localhost:4317"
service_name = "pingap-go"
sample_rate = 0.1

# Admin Interface
[admin]
enabled = true
addr = "127.0.0.1:3000"
user = "admin"
password = "changeme"

# Plugin configurations
[plugins.jwt_auth]
type = "jwt"
enabled = false
priority = 10

[plugins.jwt_auth.config]
secret = "your-secret-key-here"
algorithm = "HS256"
header = "Authorization"

[plugins.rate_limit]
type = "rate_limit"
enabled = false
priority = 20

[plugins.rate_limit.config]
rate = 100
burst = 200
key = "$remote_addr"

[plugins.request_id]
type = "request_id"
enabled = true
priority = 5

[plugins.request_id.config]
header = "X-Request-ID"
